Repository WO-Project/Front-End-Panel-Admin, pull requests merged in 2022-10, with the labels that each got.

#6 update: menambahkan fitur search pada master data
  src/layout/components/header/index.jsx
  src/navigation/vertical/menu.jsx
  src/view/pages/masterData/dataDisplay/dummyColumn.js
  src/view/pages/masterData/dataDisplay/index.jsx
Labels: bug, feat

#24 fixed conflict
  src/assets/less/pages/index.less
Labels: bug

#27 create: membuat tampilan halaman kelola user dengan styling dasar
  src/assets/less/components/custom-components/TableDisplay.less
  src/navigation/vertical/admin.jsx
  src/router/routes/Pages.jsx
  src/view/components/custom-components/TableCard.jsx
  src/view/components/custom-components/TableSearch.jsx
  src/view/pages/kelola-user/KelolaUser.jsx
  src/view/pages/kelola-user/atur-role-staff/AturRole.jsx
  src/view/pages/kelola-user/atur-role-staff/RoleColumn.js
  src/view/pages/kelola-user/atur-role-staff/RoleData.js
  src/view/pages/kelola-user/atur-role-staff/index.jsx
  src/view/pages/kelola-user/atur-role-user/AturRole.jsx
  src/view/pages/kelola-user/atur-role-user/RoleColumn.js
  src/view/pages/kelola-user/atur-role-user/RoleData.js
  src/view/pages/kelola-user/atur-role-user/index.jsx
  src/view/pages/kelola-user/crud-user/CrudUser.jsx
  src/view/pages/kelola-user/crud-user/UserColumn.js
  src/view/pages/kelola-user/crud-user/UserData.js
  src/view/pages/kelola-user/crud-user/index.jsx
  src/view/pages/master-data/MasterColumn.js
  src/view/pages/master-data/MasterData.js
  src/view/pages/master-data/MasterData.jsx
Labels: feat

#43 create: Form crud
  src/assets/less/components/custom-components/from-crud/index.less
  src/assets/less/components/custom-components/index.less
  src/router/routes/Pages.jsx
  src/view/components/custom-components/TableCard.jsx
  src/view/components/custom-components/form-crud/CardForm.jsx
  src/view/components/custom-components/form-crud/index.jsx
  src/view/pages/kelola-user/crud-user/CrudUser.jsx
  src/view/pages/kelola-user/crud-user/UserColumn.js
  src/view/pages/kelola-user/crud-user/form/create/index.jsx
  src/view/pages/kelola-user/crud-user/form/delete/index.jsx
  src/view/pages/kelola-user/crud-user/form/read/index.jsx
  src/view/pages/kelola-user/crud-user/form/update/index.jsx
  src/view/pages/kelola-user/crud-user/index.jsx
  src/view/pages/master-data/customer/Customer.jsx
  src/view/pages/master-data/customer/CustomerColumn.js
  src/view/pages/master-data/customer/form/create/index.jsx
  src/view/pages/master-data/customer/form/delete/index.jsx
  src/view/pages/master-data/customer/form/read/index.jsx
  src/view/pages/master-data/customer/form/update/index.jsx
  src/view/pages/master-data/pengantin/Pengantin.jsx
  src/view/pages/master-data/pengantin/PengantinColumn.js
  src/view/pages/master-data/pengantin/form/create/index.jsx
  src/view/pages/master-data/pengantin/form/delete/index.jsx
  src/view/pages/master-data/pengantin/form/read/index.jsx
  src/view/pages/master-data/pengantin/form/update/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/ProductColumn.js
  src/view/pages/master-data/produk-ucapan-digital/ProdukUcapanDigital.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/create/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/delete/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/read/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/update/index.jsx
  src/view/pages/master-data/wedding-organizer/WeddingOrganizer.jsx
  src/view/pages/master-data/wedding-organizer/WoColumn.js
  src/view/pages/master-data/wedding-organizer/form/create/index.jsx
  src/view/pages/master-data/wedding-organizer/form/delete/index.jsx
  src/view/pages/master-data/wedding-organizer/form/read/index.jsx
  src/view/pages/master-data/wedding-organizer/form/update/index.jsx
Labels: feat

#49 create: membuat kode dasar crud dari data api kelola user
  src/api/kelola-user/deleteUser.js
  src/api/kelola-user/getOneUser.js
  src/api/kelola-user/getUser.js
  src/api/kelola-user/postUser.js
  src/api/kelola-user/putUser.js
  src/assets/less/components/custom-components/TableDisplay.less
  src/router/routes/Pages.jsx
  src/view/components/custom-components/TableCard.jsx
  src/view/components/custom-components/TableDisplay.jsx
  src/view/components/custom-components/TableSearch.jsx
  src/view/pages/kelola-user/crud-user/CrudUser.jsx
  src/view/pages/kelola-user/crud-user/UserColumn.js
  src/view/pages/kelola-user/crud-user/form/create/index.jsx
  src/view/pages/kelola-user/crud-user/form/delete/index.jsx
  src/view/pages/kelola-user/crud-user/form/read/index.jsx
  src/view/pages/kelola-user/crud-user/form/update/index.jsx
  src/view/pages/master-data/wedding-organizer/WeddingOrganizer.jsx
Labels: feat

#54 fix: private route bug
  src/api/kelola-user/getUser.js
  src/router/Router.jsx
  src/router/routes/Pages.jsx
Labels: bug

#60 create: menambahkan fitur crud pada data pengantin
  src/api/pengantin/deleteBride.js
  src/api/pengantin/getBrides.js
  src/api/pengantin/getOneBride.js
  src/api/pengantin/postBride.js
  src/api/pengantin/putBride.js
  src/view/pages/master-data/pengantin/Pengantin.jsx
  src/view/pages/master-data/pengantin/PengantinColumn.js
  src/view/pages/master-data/pengantin/PengantinData.js
  src/view/pages/master-data/pengantin/form/create/index.jsx
  src/view/pages/master-data/pengantin/form/delete/index.jsx
  src/view/pages/master-data/pengantin/form/read/index.jsx
  src/view/pages/master-data/pengantin/form/update/index.jsx
  src/view/pages/master-data/pengantin/form2/create/index.jsx
  src/view/pages/master-data/pengantin/form2/read/index.jsx
  src/view/pages/master-data/pengantin/form2/update/index.jsx
Labels: feat

#64 feat: Fitur CRUD WO master data
  src/api/wedding-organizer/deleteWeddingOrganizer.js
  src/api/wedding-organizer/getOneWeddingOrganizer.js
  src/api/wedding-organizer/getWeddingOrganizers.js
  src/api/wedding-organizer/postWeddingOrganizer.js
  src/api/wedding-organizer/putWeddingOrganizer.js
  src/view/pages/master-data/wedding-organizer/WeddingOrganizer.jsx
  src/view/pages/master-data/wedding-organizer/WoColumn.js
  src/view/pages/master-data/wedding-organizer/WoData.js
  src/view/pages/master-data/wedding-organizer/form/create/index.jsx
  src/view/pages/master-data/wedding-organizer/form/delete/index.jsx
  src/view/pages/master-data/wedding-organizer/form/read/index.jsx
  src/view/pages/master-data/wedding-organizer/form/update/index.jsx
Labels: feat

#67 Create: Membuat fitur CRUD pada halaman produk ucapan master data
  src/api/artikel/category/index.js
  src/api/artikel/category/postCategory.js
  src/api/artikel/getArticleDetail.js
  src/api/artikel/index.js
  src/api/artikel/postArticles.js
  src/api/artikel/updateArticle.js
  src/api/produk-ucapan/deleteProduct.js
  src/api/produk-ucapan/getProducts.js
  src/api/produk-wo/getOneProduct.js
  src/api/produk-wo/getProducts.js
  src/api/produk-wo/postProduct.js
  src/api/produk-wo/product-categories/getProductCategory2.js
  src/api/produk-wo/putProduct.js
  src/assets/less/components/custom-components/TableCard.less
  src/navigation/vertical/admin.jsx
  src/router/routes/KelolaArtikel/Create.js
  src/router/routes/KelolaArtikel/GetAll.js
  src/router/routes/KelolaArtikel/GetDetail.js
  src/router/routes/KelolaArtikel/Update.js
  src/router/routes/KelolaArtikel/index.js
  src/router/routes/KelolaProdukWO/index.js
  src/router/routes/KelolaUser/index.js
  src/router/routes/MasterData/index.js
  src/router/routes/Pages.jsx
  src/view/components/custom-components/TableCard.jsx
  src/view/components/custom-components/TableDisplay.jsx
  src/view/pages/artikel/artikel-kategori/UserColumn.js
  src/view/pages/artikel/artikel-kategori/form/create/index.jsx
  src/view/pages/artikel/artikel-kategori/index.jsx
  src/view/pages/artikel/artikel/UserColumn.js
  src/view/pages/artikel/artikel/form/create/index.jsx
  src/view/pages/artikel/artikel/index.jsx
  src/view/pages/dashboard/dummy2.js
  src/view/pages/dashboard/dummyColumns2.js
  src/view/pages/dashboard/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/ProductColumn.js
  src/view/pages/master-data/produk-ucapan-digital/ProductData.js
  src/view/pages/master-data/produk-ucapan-digital/ProdukUcapanDigital.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/create/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/delete/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/read/index.jsx
  src/view/pages/master-data/produk-ucapan-digital/form/update/index.jsx
Labels: feat
